#!/bin/sh
# /etc/X11/xinit/xinitrc
# global xinitrc file, used by all X sessions started by xinit (startx)
# invoke global X session script
. /etc/X11/Xsession

xset +fp /usr/share/fonts/misc # Inform the X server of new directories          
                                                                                 
xset fp rehash                # Forces a new rescan                              
                                                                                 
compton --config ~/.config/compton.conf -b &                                     
                                                                                 
dunst &                                                                          
                                                                                 
xset b off &                                                                     
                                                                                 
#volumeicon &                                                                    
                                                                                 
xset s 180 &                                                                     
                                                                                 
xss-lock -- i3lock -i $HOME/.wl/lock.png &                                       
                                                                                 
#anamnesis --start &                                                              
                                                                                 
#mpd &                                                                            
                                                                                 
#mpdscribble &                                                                    
                                                                                 
#clipit &                                                                        
                                                                                 
#nm-applet &                                                                     
                                                                                 
#blueman-applet &                                                                
                                                                                 
unclutter &                                                                      
                                                                                 
xrdb ~/.Xdefaults                                                    
                                                                                 
#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
#export GPG_AGENT_INFO SSH_AUTH_SOCK                                             
                                                                                 
#eval $(gpg-agent --daemon)                                                       
                                                                                 
# exec gnome-session                                                             
# exec startkde                                                                  
# exec startxfce4                                                                
# ...or the Window Manager of your choice                                        
#exec i3                                                                         

xbacklight = 10
xinput set-prop 11 "Synaptics Two-Finger Scrolling" 1, 1
xinput set-prop 11 "Synaptics Palm Detection" 1
xinput set-prop 11 "Synaptics Palm Dimensions" 5, 80

exec i3 -V >> ~/logs/i3/i3log-$(date +'%F-%k-%M-%S') 2>&1         

